from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from io import BytesIO
from datetime import datetime


PRIMARY   = colors.HexColor("#1D9E75")
DARK      = colors.HexColor("#1a1a2e")
LIGHT_BG  = colors.HexColor("#f0f7ff")
MUTED     = colors.HexColor("#666666")
WHITE     = colors.white


def build_pdf(result: dict, location: dict) -> bytes:
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "Title",
        parent=styles["Normal"],
        fontSize=24,
        fontName="Helvetica-Bold",
        textColor=DARK,
        alignment=TA_CENTER,
        spaceAfter=6,
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=12,
        fontName="Helvetica",
        textColor=MUTED,
        alignment=TA_CENTER,
        spaceAfter=4,
    )

    section_style = ParagraphStyle(
        "Section",
        parent=styles["Normal"],
        fontSize=13,
        fontName="Helvetica-Bold",
        textColor=PRIMARY,
        spaceBefore=16,
        spaceAfter=8,
    )

    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=11,
        fontName="Helvetica",
        textColor=DARK,
        spaceAfter=6,
        leading=16,
    )

    elements = []

    # header
    elements.append(Spacer(1, 0.5*cm))
    elements.append(Paragraph("SolarIQ", title_style))
    elements.append(Paragraph("Solar Feasibility Report", subtitle_style))
    elements.append(Paragraph(
        f"Generated on {datetime.now().strftime('%d %B %Y at %H:%M')}",
        subtitle_style
    ))
    elements.append(Spacer(1, 0.3*cm))
    elements.append(HRFlowable(
        width="100%", thickness=2,
        color=PRIMARY, spaceAfter=16
    ))

    # location
    elements.append(Paragraph("Location", section_style))
    elements.append(Paragraph(
        f"Latitude: {location['lat']:.4f} | Longitude: {location['lng']:.4f}",
        body_style
    ))

    # solar prediction
    elements.append(Paragraph("Solar Radiation", section_style))
    radiation_data = [
        ["Metric", "Value"],
        ["Instant Radiation",   f"{result['predicted_radiation']} W/m²"],
        ["Annual Radiation",    f"{result['annual_radiation_kwh_m2']} kWh/m²/year"],
    ]
    elements.append(_build_table(radiation_data))

    # energy & financials
    elements.append(Paragraph("Energy & Financial Analysis", section_style))
    financial_data = [
        ["Metric", "Value"],
        ["Annual Energy Generation", f"{result['annual_energy_kwh']} kWh"],
        ["Annual Savings",           f"₹ {result['annual_savings']:,.0f}"],
        ["System Cost",              f"₹ {result['system_cost']:,.0f}"],
        ["Payback Period",
         f"{result['payback_years']} years" if result['payback_years'] else "N/A"],
    ]
    elements.append(_build_table(financial_data))

    # environmental
    elements.append(Paragraph("Environmental Impact", section_style))
    env_data = [
        ["Metric", "Value"],
        ["CO₂ Saved per Year",   f"{result['co2_saved_kg']:,.0f} kg"],
        ["Equivalent Trees",     f"{result['co2_saved_kg'] / 21:.0f} trees planted"],
        ["10-year CO₂ Savings",  f"{result['co2_saved_kg'] * 10:,.0f} kg"],
    ]
    elements.append(_build_table(env_data))

    # recommendation
    elements.append(Paragraph("Recommendation", section_style))
    recommendation = _build_recommendation(result)
    elements.append(Paragraph(recommendation, body_style))

    # footer
    elements.append(Spacer(1, 1*cm))
    elements.append(HRFlowable(
        width="100%", thickness=1,
        color=MUTED, spaceAfter=8
    ))
    elements.append(Paragraph(
        "Generated by SolarIQ — Location-Aware Solar Energy Estimation Platform",
        ParagraphStyle("Footer", parent=styles["Normal"],
                       fontSize=9, textColor=MUTED, alignment=TA_CENTER)
    ))

    doc.build(elements)
    return buffer.getvalue()


def _build_table(data: list) -> Table:
    table = Table(data, colWidths=[9*cm, 8*cm])
    table.setStyle(TableStyle([
        # header row
        ("BACKGROUND",  (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR",   (0, 0), (-1, 0), WHITE),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, 0), 11),
        ("ALIGN",       (0, 0), (-1, 0), "CENTER"),
        ("TOPPADDING",  (0, 0), (-1, 0), 8),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),

        # data rows
        ("FONTNAME",    (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",    (0, 1), (-1, -1), 10),
        ("TEXTCOLOR",   (0, 1), (-1, -1), DARK),
        ("TOPPADDING",  (0, 1), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),

        # alternating row colors
        ("BACKGROUND",  (0, 1), (-1, 1), LIGHT_BG),
        ("BACKGROUND",  (0, 3), (-1, 3), LIGHT_BG),

        # grid
        ("GRID",        (0, 0), (-1, -1), 0.5, colors.HexColor("#e0e0e0")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [WHITE, LIGHT_BG]),
    ]))
    return table


def _build_recommendation(result: dict) -> str:
    payback = result.get("payback_years")
    savings = result.get("annual_savings", 0)
    radiation = result.get("predicted_radiation", 0)

    if payback and payback <= 5:
        verdict = "Excellent investment"
        reason  = (f"With a payback period of just {payback} years and annual "
                   f"savings of ₹{savings:,.0f}, this location offers outstanding "
                   f"solar returns. We strongly recommend proceeding.")
    elif payback and payback <= 8:
        verdict = "Good investment"
        reason  = (f"A payback period of {payback} years with ₹{savings:,.0f} "
                   f"annual savings makes this a solid solar investment. "
                   f"Recommended with standard panel efficiency.")
    elif payback and payback <= 12:
        verdict = "Moderate investment"
        reason  = (f"The {payback}-year payback period is acceptable but longer "
                   f"than ideal. Consider higher efficiency panels or increasing "
                   f"roof area to improve returns.")
    else:
        verdict = "Review recommended"
        reason  = (f"The payback period exceeds 12 years at this location. "
                   f"Solar radiation of {radiation:.1f} W/m² may be insufficient "
                   f"for optimal returns. Consider reassessing panel placement.")

    return f"{verdict}: {reason}"